(() => {
  'use strict';
  const $=id=>document.getElementById(id),form=$('request');let endpoint='';
  const prompts={'Masonry & brickwork':['What needs repair?','Approximate wall or step size'],'Roofing':['Roof type / number of stories','Where have you noticed a leak?'],'Kitchen remodeling':['Keep the existing layout?','Cabinets, counters or a full remodel?'],'Bathroom remodeling':['Shower, tub or full bathroom?','Any access or building requirements?'],'Concrete & paving':['Approximate area / dimensions','Repair or replace?'],'Other repairs':['What needs attention?']};
  function questions(){$('questions').replaceChildren();(prompts[$('service').value]||[]).forEach((text,i)=>{const l=document.createElement('label');l.textContent=text;const field=document.createElement('input');field.name='question'+i;field.maxLength=500;field.dataset.question=text;l.append(field);$('questions').append(l);});$('reviewBox').hidden=true;}
  $('service').onchange=questions;questions();form.addEventListener('input',()=>{$('reviewBox').hidden=true;});
  function summary(){const data=new FormData(form);return ['Estimate request — Hammer Brick & Home',...['service','name','phone','location','timing','contactTime','details'].map(key=>key+': '+data.get(key)),...[...$('questions').querySelectorAll('input')].filter(x=>x.value).map(x=>x.dataset.question+': '+x.value)].join('\n');}
  $('review').onclick=()=>{if(!form.reportValidity())return;$('summary').textContent=summary();$('textRequest').href='sms:+19295955300?body='+encodeURIComponent(summary());$('reviewBox').hidden=false;};
  fetch('/site-data/homepage.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{if(/^https:\/\//i.test(data.estimateFormEndpoint||'')){const url=new URL(data.estimateFormEndpoint);if(url.username||url.password)return;endpoint=url.href;$('send').hidden=false;$('photoLabel').hidden=false;$('method').textContent='Review your request, then send it online or open a text message. Online submissions go through '+url.hostname+'.';}}).catch(()=>{});
  form.onsubmit=async e=>{e.preventDefault();if(!endpoint||!form.reportValidity())return;const files=[...$('photos').files];if(files.length>5||files.some(f=>f.size>5*1024*1024||!/^image\/(jpeg|png|webp)$/.test(f.type))){$('result').textContent='Use up to 5 JPG, PNG or WebP photos under 5 MB each.';return;}$('send').disabled=true;try{const data=new FormData(form);data.set('requestSummary',summary());const response=await fetch(endpoint,{method:'POST',body:data,headers:{Accept:'application/json'}});if(!response.ok)throw Error();$('result').textContent='The form service accepted your request. We will contact you to discuss the work.';}catch{$('result').textContent='Could not confirm delivery. Please use the text message option or call 929-595-5300.';}finally{$('send').disabled=false;}};
})();
