/* Homepage-only optional enhancements. Disabled settings are a strict no-op. */
(() => {
  'use strict';
  if (!['/','/index.html'].includes(location.pathname)) return;
  const make=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
  const safe=v=>{if(typeof v!=='string'||/[\s\\]/.test(v))return false;if(/^\/(?!\/)/.test(v))return !/(?:^|\/)\.\.?(?:\/|$)/.test(v);try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}};
  const draftImage=v=>{try{return typeof v==='string'&&v.startsWith('blob:'+location.origin+'/')&&parent!==window&&parent.location.origin===location.origin&&/^\/admin\/(studio|workshop)\.html$/.test(parent.location.pathname);}catch{return false;}};
  const imagePath=v=>safe(v)||draftImage(v)?v:typeof v==='string'&&!v.includes('/')&&/\.(png|jpe?g|webp|avif)$/i.test(v)?'/images/'+encodeURIComponent(v):'';
  const get=async path=>{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error('Unavailable');return r.json();};
  const active=p=>p&&p.active!==false&&!['draft','archived','scheduled'].includes(p.publishStatus);
  const patterns={masonry:/masonry|brick|stone|paver|step|stoop|concrete|driveway|walkway/i,roofing:/roof|gutter|chimney|flashing|skylight/i,remodeling:/remodel|kitchen|bath|interior|floor|painting|deck|carpentry/i,waterproofing:/waterproof|leak|moisture|parging|seal/i,'commercial / co-op':/commercial|co-?op|condo|storefront|office|restaurant/i};
  const textOf=r=>[r.title,r.label,r.summary,r.serviceLabel,r.service,r.serviceSlug,r.projectType,...(r.tags||[])].filter(Boolean).join(' ');
  const match=(r,category)=>!category||(patterns[category.toLowerCase()]||{test:t=>t.toLowerCase().includes(category.toLowerCase())}).test(textOf(r));
  function image(path,alt){const src=imagePath(path);if(!src)return null;const img=make('img');img.src=src;img.alt=alt||'';img.loading='lazy';img.decoding='async';img.width=600;img.height=400;return img;}
  function styles(){if(document.getElementById('hbWorkshopStyles'))return;const s=make('style');s.id='hbWorkshopStyles';s.textContent='.hb-workshop{box-sizing:border-box;margin:24px auto;padding:24px;width:min(1180px,calc(100% - 32px));background:#fffdf7;color:#19342e;border:1px solid #bdb792;border-radius:14px;font:16px/1.6 system-ui}.hb-workshop *{box-sizing:border-box}.hb-workshop h2{color:#19342e;font:700 clamp(24px,4vw,34px)/1.2 Georgia}.hb-workshop a{color:#225242}.hb-workshop .hb-options{display:flex;gap:8px;flex-wrap:wrap}.hb-workshop button{background:#f0f2e8;color:#19342e;border:1px solid #6e846c;border-radius:8px;padding:10px 14px;min-height:44px;cursor:pointer}.hb-workshop button[aria-pressed=true]{background:#193c33;color:#fff}.hb-workshop :focus-visible{outline:3px solid #a27625;outline-offset:3px}.hb-workshop .hb-results{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(250px,100%),1fr));gap:18px;margin-top:18px}.hb-workshop article{padding:15px;border:1px solid #d4dacb;border-radius:9px;background:#fff}.hb-workshop img{width:100%;height:190px;object-fit:cover;border-radius:6px}.hb-workshop h3{font:700 21px/1.3 Georgia;color:#19342e}.hb-workshop p{color:#344f42}.hb-workshop figure{margin:0}.hb-workshop .hb-pair{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hb-workshop .hb-pair img{height:160px}.hb-workshop .hb-pair figcaption{font-size:12px;color:#344f42}.hb-workshop.hb-notice{border-left:6px solid #ab761c}.hb-trust-list{display:flex;gap:18px;flex-wrap:wrap}.hb-trust-list li{padding:8px}.hb-workshop[hidden]{display:none!important}';document.head.append(s);}
  function insert(el){const hero=document.getElementById('homeHero');if(hero)hero.after(el);else(document.querySelector('main')||document.body).prepend(el);}
  async function chooser(c){const [projectData,galleryData,reviewData]=await Promise.all([get('/site-data/projects.json'),get('/gallery.json'),get('/site-data/reviews.json')]);const items=[];
    for(const p of projectData.projects||[])if(active(p)&&p.showOnHomepage===true&&p.title)items.push({type:'project',...p});
    for(const p of galleryData.homePairs||[])if(active(p)&&p.label&&imagePath(p.before)&&imagePath(p.after))items.push({type:'pair',...p});
    for(const r of reviewData.reviews||[])if(active(r)&&r.showOnHomepage!==false&&(r.review||r.text))items.push({type:'review',...r});
    const section=make('section');section.id='hbProjectChooser';section.className='hb-workshop';section.setAttribute('aria-labelledby','hbChooserTitle');const h=make('h2',c.projectChooserHeading||'Explore our work');h.id='hbChooserTitle';const options=make('div');options.className='hb-options';options.setAttribute('role','group');options.setAttribute('aria-label','Choose project type');const counter=make('p');counter.setAttribute('role','status');const results=make('div');results.className='hb-results';const more=make('button','Show more matching work');more.type='button';let selected='',limit=6;
    function render(){results.replaceChildren();const matches=items.filter(r=>match(r,selected));for(const r of matches.slice(0,limit)){const card=make('article');card.append(make('small',r.type==='review'?'Customer review':r.type==='pair'?'Before & after':'Project'));if(r.type==='project'){const img=image(r.coverImage,r.imageAlt||r.title);if(img)card.append(img);card.append(make('h3',r.title),make('p',r.summary||''));if(safe(r.ctaUrl)){const a=make('a',r.ctaText||'Read project');a.href=r.ctaUrl;card.append(a);}}else if(r.type==='pair'){card.append(make('h3',r.label));const pair=make('div');pair.className='hb-pair';for(const [key,label] of [['before','Before'],['after','After']]){const f=make('figure'),img=image(r[key],r[key+'Alt']||label+': '+r.label);if(img)f.append(img);f.append(make('figcaption',label));pair.append(f);}card.append(pair);}else card.append(make('blockquote',r.review||r.text),make('strong',r.name||'Customer'),make('p',r.service||''));results.append(card);}counter.textContent=matches.length?Math.min(limit,matches.length)+' of '+matches.length+' matching items.':'No matching items published yet. Choose All work or explore the service pages.';more.hidden=matches.length<=limit;for(const b of options.children)b.setAttribute('aria-pressed',String(b.dataset.category===selected));}
    for(const category of ['',...(Array.isArray(c.projectChooserCategories)?c.projectChooserCategories.slice(0,12):[])]){const b=make('button',category||'All work');b.type='button';b.dataset.category=category;b.onclick=()=>{selected=category;limit=6;render();};options.append(b);}more.onclick=()=>{limit+=6;render();};section.append(h,options,counter,results,more);insert(section);render();}
  function notice(e){if(!e?.enabled||!e.title||!e.message)return;const expiry=Date.parse(e.expiresAt);if(e.autoExpire&&(!Number.isFinite(expiry)||expiry<=Date.now()))return;const box=make('aside');box.id='hbEmergencyNotice';box.className='hb-workshop hb-notice';box.setAttribute('aria-label','Service notice');box.append(make('h2',e.title),make('p',e.message));if(e.linkText&&safe(e.linkUrl)){const a=make('a',e.linkText);a.href=e.linkUrl;box.append(a);}insert(box);if(e.autoExpire){const timer=setInterval(()=>{if(Date.now()>=expiry){box.remove();clearInterval(timer);}},30000);}}
  function trust(c){if(!c.publicTrustEnabled)return;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const rows=(c.publicTrust||[]).filter(r=>r.ownerVerified===true&&/^\d{4}-\d{2}-\d{2}$/.test(r.validUntil)&&r.validUntil>=today&&r.label);if(!rows.length)return;const box=make('section');box.id='hbPublicTrust';box.className='hb-workshop';box.append(make('h2','Credentials at a glance'));const list=make('ul');list.className='hb-trust-list';for(const r of rows)list.append(make('li',r.label+(r.number?' · '+r.number:'')+' · valid through '+r.validUntil));box.append(list,make('small','Owner-verified summary. Ask for documentation and project-specific coverage details.'));(document.querySelector('main')||document.body).append(box);}
  function membership(m){if(!m?.overrideEnabled)return;const apply=()=>{const node=document.getElementById('membershipServicesSection');if(!node)return;if(m.hideUntilActivated&&!m.activated){node.style.setProperty('display','none','important');node.setAttribute('data-workshop-hidden','true');return;}const s=node.querySelector('.card-status'),y=node.querySelector('.card-number');if(s&&m.status)s.textContent=m.status;if(y&&/^\d{4}$/.test(m.year))y.textContent='•••• •••• •••• '+m.year;};apply();let count=0;const interval=setInterval(()=>{apply();if(++count>=20)clearInterval(interval);},300);}
  const start=async()=>{try{const c=await get('/site-data/owner-tools.json');if(c.version!==1)return;if(!c.projectChooserEnabled&&!c.emergency?.enabled&&!c.publicTrustEnabled&&!c.membership?.overrideEnabled)return;styles();notice(c.emergency);trust(c);membership(c.membership);if(c.projectChooserEnabled)await chooser(c);}catch(e){console.warn('Optional Workshop features unavailable; normal homepage remains active.');}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
