/* Visual Control 3: owner-only draft tools. No repository writes or publishing. */
(() => {
  'use strict';
  const $ = id => document.getElementById(id), A = window.HammerVisualControlV2;
  const clone = x => JSON.parse(JSON.stringify(x));
  const HOME = 'site-data/homepage.json', DESIGN = 'site-data/design.json', PROJECTS = 'site-data/projects.json';
  const KEY = 'hammer-control-3-draft', CAMPAIGNS = 'hammer-control-3-campaigns';
  const generated = new Map();
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const slug = s => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const home = () => A.files()[HOME], design = () => A.files()[DESIGN];
  const project = () => A.files()[PROJECTS].projects[A.selectedProject()];
  const textFields = {homeHeroTitle:'heroTitle',homeHeroText:'heroText',homeHeroPrimary:'heroPrimaryButtonText',homeHeroSecondary:'heroSecondaryButtonText',processHeading:'processHeading',beforeAfterHeading:'beforeAfterHeading',beforeAfterNote:'beforeAfterNote',guaranteeTitle:'guaranteeTitle',guaranteeText:'guaranteeText',reviewHeading:'reviewHeading',reviewIntro:'reviewIntro',serviceAreaHeading:'serviceAreaHeading',serviceAreaIntro:'serviceAreaIntro',tierHeading:'tierHeading',tierText:'tierText',adminAnnouncementText:'announcementText'};
  function panel(id,title){const d=A.make('details'),s=A.make('summary',title);d.id=id;d.append(s);$('editor').insertBefore(d,document.querySelector('.download-panel'));return d;}
  function para(root,text){root.append(A.make('p',text));}
  function input(root,label,value='',multiline=false){const l=A.make('label',label),el=A.make(multiline?'textarea':'input');el.value=value;l.append(el);root.append(l);return el;}
  function safeUrl(value){return /^\/(?!\/)/.test(value) || /^https:\/\//i.test(value);}
  function storage(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}}
  function dataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob);});}
  async function bundle(){return {format:'hammer-control-3',savedAt:new Date().toISOString(),files:clone(A.files()),generated:Object.fromEntries(generated),assets:await Promise.all([...A.assets].map(async([path,v])=>({path,data:await dataUrl(v.file)})))};}
  async function restore(b){
    if(!b||b.format!=='hammer-control-3'||!b.files)throw Error('Choose a Control 3 backup.');
    A.validBundle({format:'hammer-visual-control-v2',files:b.files});
    for(const [path,key] of [[PROJECTS,'projects'],['site-data/reviews.json','reviews'],['site-data/pages.json','pages'],['gallery.json','homePairs']])if(!Array.isArray(b.files[path][key]))throw Error('Invalid list in '+path);
    const loaded=[];
    for(const asset of b.assets||[]){if(!/^\/images\/owner\/[a-z0-9._-]+$/i.test(asset.path)||!/^data:image\/(png|jpeg|webp|avif);base64,/.test(asset.data))throw Error('Invalid backup image.');const response=await fetch(asset.data);const blob=await response.blob();if(blob.size>12*1024*1024)throw Error('Backup image too large.');loaded.push([asset.path,{file:blob,url:URL.createObjectURL(blob)}]);}
    for(const path of Object.keys(b.generated||{}))if(!/^project-[a-z0-9-]+\.html$/.test(path)&&!/^project-[a-z0-9-]+-social\.txt$/.test(path))throw Error('Invalid generated filename.');
    A.replace({format:'hammer-visual-control-v2',files:b.files});
    A.assets.forEach(v=>URL.revokeObjectURL(v.url));A.assets.clear();loaded.forEach(([p,v])=>A.assets.set(p,v));generated.clear();Object.entries(b.generated||{}).forEach(([p,v])=>generated.set(p,v));A.preview();A.status('Draft and its images recovered. Review before downloading.');
  }
  // Standard uncompressed ZIP: one download, preserves all folder names, no third-party dependency.
  const encoder=new TextEncoder();
  function crc(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
  function zip(entries){let offset=0;const local=[],central=[];for(const [name,bytes] of entries){const n=encoder.encode(name),h=new Uint8Array(30+n.length),v=new DataView(h.buffer),sum=crc(bytes);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,sum,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,n.length,true);h.set(n,30);local.push(h,bytes);const c=new Uint8Array(46+n.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,sum,true);cv.setUint32(20,bytes.length,true);cv.setUint32(24,bytes.length,true);cv.setUint16(28,n.length,true);cv.setUint32(42,offset,true);c.set(n,46);central.push(c);offset+=h.length+bytes.length;}const end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,entries.length,true);ev.setUint16(10,entries.length,true);ev.setUint32(12,central.reduce((s,c)=>s+c.length,0),true);ev.setUint32(16,offset,true);return new Blob([...local,...central,end],{type:'application/zip'});}
  function saveBlob(name,blob){const url=URL.createObjectURL(blob),a=A.make('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  function diff(){return A.changedPaths().map(path=>{const before=A.original()[path]||{},after=A.files()[path];const keys=[...new Set([...Object.keys(before),...Object.keys(after)])].filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k]));return path+'\n  Changed: '+keys.join(', ');}).join('\n\n');}
  async function exportZip(){
    for(const [path,html] of generated){if(!path.endsWith('.html'))continue;const p=A.files()[PROJECTS].projects.find(x=>x.ctaUrl==='/'+path);if(!p){generated.delete(path);generated.delete(path.replace('.html','-social.txt'));continue;}try{if(buildStory(p).html!==html)return A.status('Project details changed. Rebuild '+p.title+' in section 10 before downloading.');}catch(e){return A.status(e.message);}}
    const entries=[],add=(p,t)=>entries.push([p,encoder.encode(t)]);
    for(const path of A.changedPaths()){const text=JSON.stringify(A.files()[path],null,2)+'\n';add('UPLOAD/'+path,text);add('TEXT-COPIES/'+path+'.txt',text);}
    generated.forEach((text,path)=>{add('UPLOAD/'+path,text);add('TEXT-COPIES/'+path+'.txt',text);});
    for(const [path,v] of A.assets)entries.push(['UPLOAD'+path,new Uint8Array(await v.file.arrayBuffer())]);
    add('READ-ME.txt','Upload the CONTENTS of UPLOAD into your repository root, keeping folders. Do not upload TEXT-COPIES. Text copies are for editing; remove only the final .txt before uploading. Nothing has been published.\n\n'+diff()+'\n\nGenerated files:\n'+[...generated.keys()].join('\n')+'\n\nImages:\n'+[...A.assets.keys()].join('\n'));
    saveBlob('HammerBrick-Draft-Changes.zip',zip(entries));A.status('One ZIP downloaded with exact paths, images and text copies.');
  }
  function renderPhotoOrder(){const root=$('photoOrder');root.replaceChildren();const p=project();if(!p)return;for(const key of ['midProcessImages','additionalImages']){const arr=p[key]||[];root.append(A.make('h4',key==='midProcessImages'?'In-progress photos':'Additional photos'));const list=A.make('ol');list.className='sortable';arr.forEach((path,i)=>{const li=A.make('li'),handle=A.button('↕',()=>{});handle.className='handle';handle.setAttribute('aria-label','Drag photo '+(i+1));li.append(handle);const img=A.make('img');img.src=A.assets.get(path)?.url||path;img.alt='Photo '+(i+1);img.width=70;img.height=60;img.style.objectFit='cover';li.append(img,A.make('small',path));for(const n of [-1,1]){const b=A.button(n<0?'↑':'↓',()=>{A.mutate(()=>A.moveIn(arr,i,i+n));renderPhotoOrder();});b.disabled=i+n<0||i+n>=arr.length;li.append(b);}li.append(A.button('Remove from draft',()=>{A.mutate(()=>arr.splice(i,1));renderPhotoOrder();}));list.append(li);handle.onpointerdown=e=>{if(e.button!==0)return;handle.setPointerCapture(e.pointerId);let target=i;handle.onpointermove=ev=>{const row=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('li');if(row?.parentElement===list)target=[...list.children].indexOf(row);};handle.onpointerup=()=>{handle.onpointermove=null;handle.onpointerup=null;A.mutate(()=>A.moveIn(arr,i,target));renderPhotoOrder();};handle.onpointercancel=()=>{handle.onpointermove=null;handle.onpointerup=null;};};});root.append(list);}}
  function buildStory(p){
    if(!p||!p.title?.trim()||!p.summary?.trim()||!p.imageAlt?.trim()||!p.coverImage||!safeUrl(p.coverImage))throw Error('Add a title, work summary, cover photo and photo description first.');
    if(!p.realProjectConfirmed)throw Error('Confirm these are real project facts and photos before building a job story.');
    const name=slug(p.slug||p.title);if(!name)throw Error('Enter a project title.');const path='project-'+name+'.html',url='https://www.hammerbrickhome.com/'+path;
    const live=p.active!==false&&p.publishStatus==='live';
    const schema={'@context':'https://schema.org','@type':'WebPage',name:p.seoTitle||p.title,url,description:p.seoDescription||p.summary,mainEntity:{'@type':'CreativeWork',name:p.title,description:p.summary,image:new URL(p.coverImage,'https://www.hammerbrickhome.com').href}};
    const section=(title,text)=>text?'<section><h2>'+esc(title)+'</h2><p>'+esc(text)+'</p></section>':'';
    const image=(path,alt)=>path&&safeUrl(path)?'<figure><img loading="lazy" src="'+esc(path)+'" alt="'+esc(alt)+'"></figure>':'';
    const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(p.seoTitle||p.title)+' | Hammer Brick &amp; Home</title><meta name="description" content="'+esc(p.seoDescription||p.summary)+'"><meta name="robots" content="'+(live?'index,follow':'noindex,follow')+'"><link rel="canonical" href="'+url+'"><meta property="og:image" content="'+esc(schema.mainEntity.image)+'"><script type="application/ld+json">'+JSON.stringify(schema).replace(/</g,'\\u003c')+'</script><style>body{margin:0;background:#faf7ef;color:#172b32;font:18px/1.7 system-ui}header,main,footer{max-width:1000px;margin:auto;padding:24px}a{color:#245d52}h1{font:clamp(32px,6vw,58px)/1.12 Georgia}img{max-width:100%;height:auto;border-radius:14px}figure{margin:20px 0}section{border-top:1px solid #c9bfae;padding:20px 0}p{white-space:pre-line}.cta{display:inline-block;background:#173e36;color:white;padding:14px 22px;border-radius:9px}</style></head><body><header><a href="/">Hammer Brick &amp; Home LLC</a> · <a href="/gallery.html">Our work</a></header><main><h1>'+esc(p.title)+'</h1><p>'+esc([p.serviceLabel,p.areaLabel,p.neighborhood].filter(Boolean).join(' · '))+'</p>'+image(p.coverImage,p.imageAlt)+'<p>'+esc(p.summary)+'</p>'+section('The problem',p.storyProblem)+section('Our solution',p.storySolution)+image(p.beforeImage,p.beforeAlt||'Before: '+p.imageAlt)+section('The finished result',p.storyResult)+image(p.afterImage,p.afterAlt||'After: '+p.imageAlt)+'<a class="cta" href="/estimate-request.html">Discuss a similar project</a></main><footer><a href="tel:+19295955300">929-595-5300</a> · <a href="/">www.hammerbrickhome.com</a></footer></body></html>';
    return {path,html,url,live};
  }
  function generateStory(){try{const p=project(),result=buildStory(p);const existing=generated.has(result.path)||A.files()['site-data/pages.json'].pages.some(x=>x.url==='/'+result.path);if(existing&&!confirm('Replace the draft story at '+result.path+'?'))return;generated.set(result.path,result.html);generated.set(result.path.replace('.html','-social.txt'),p.title+'\n\n'+p.summary+'\n\n'+result.url+'\n\nHammer Brick & Home LLC · 929-595-5300\nReview facts and photos before posting.');A.mutate(()=>{p.ctaUrl='/'+result.path;p.ctaText='See the project story';const items=A.files()['site-data/pages.json'].pages;const row={slug:result.path.replace('.html',''),url:'/'+result.path,menuLabel:p.title,seoTitle:p.seoTitle||p.title,seoDescription:p.seoDescription||p.summary,socialImage:p.coverImage,active:result.live,allowIndexing:result.live,showInSitemap:result.live,structuredDataType:'page'};const index=items.findIndex(x=>x.url===row.url);if(index<0){items.push(row);$('seoPage').replaceChildren();}else items[index]=row;if(p.beforeImage&&p.afterImage){const pairs=A.files()['gallery.json'].homePairs;let pair=pairs.find(x=>x.storyUrl===row.url);if(!pair){pair={};pairs.push(pair);}Object.assign(pair,{storyUrl:row.url,label:p.title,before:p.beforeImage,after:p.afterImage,beforeAlt:p.beforeAlt||'Before: '+p.imageAlt,afterAlt:p.afterAlt||'After: '+p.imageAlt,summary:p.storyResult||p.summary,active:result.live,sliderStart:50});}});A.status('Project page, comparison and social draft prepared. Download the ZIP; draft pages stay noindex until rebuilt as live.');}catch(e){A.status(e.message);}}
  async function audit(){const out=$('auditResults');out.textContent='Checking draft paths…';const issues=[],paths=new Set();const visit=(obj,key='')=>{if(Array.isArray(obj)){obj.forEach(x=>visit(x,key));return;}if(obj&&typeof obj==='object'){Object.entries(obj).forEach(([k,v])=>visit(v,k));return;}if(typeof obj==='string'&&/^\/(?!\/)/.test(obj)&&/image|logo|url|link|photo/i.test(key))paths.add(obj);};visit(A.files());
    for(const [i,p] of A.files()[PROJECTS].projects.entries())if(p.active!==false&&p.publishStatus==='live'){A.projectWarnings(p).forEach(w=>issues.push('Project '+(i+1)+': '+w));if(!p.realProjectConfirmed)issues.push('Project '+(i+1)+': confirm photos show real completed work before generating a story.');}
    const pages=A.files()['site-data/pages.json'].pages;const titles=new Set();for(const p of pages){if(p.seoTitle&&titles.has(p.seoTitle))issues.push('Duplicate title: '+p.seoTitle);titles.add(p.seoTitle);if(p.active!==false&&p.allowIndexing===false)issues.push(p.url+': indexing is off.');}
    for(const row of home().sectionVisibility||[])if(home().sectionVisibilityEnabled&&(row.showDesktop===false||row.showMobile===false))issues.push(row.section+': hidden on '+(row.showDesktop===false?'desktop ':'')+(row.showMobile===false?'mobile':''));
    for(const path of paths){if(A.assets.has(path)||generated.has(path.slice(1)))continue;try{const response=await fetch(path,{method:'HEAD',cache:'no-store',signal:AbortSignal.timeout(6000)});if(!response.ok)issues.push(path+' — HTTP '+response.status);}catch{issues.push(path+' — could not verify');}}
    out.textContent=(issues.length?issues.join('\n'):'No issues found in these checks.')+'\n\nChecked '+paths.size+' local URLs. External URLs, Google indexing and visual appearance need separate review.';}
  function init(){
    if(!A.files()[HOME]){setTimeout(init,150);return;}
    document.querySelector('h1').textContent='Visual Site Control 3.0';
    // Establish normalized baseline without treating rendering defaults as owner edits.
    Object.assign(A.original(),clone(A.files()));
    const edit=panel('step8','8 · Click-to-edit and homepage wording');para(edit,'Turn on click-to-edit, then select a heading, button, logo or picture in the preview. Changes stay in your draft.');const click=input(edit,'Click-to-edit');click.type='checkbox';click.id='clickEdit';const fields=A.make('div');fields.id='directFields';fields.className='field-grid';edit.append(fields);
    const select=A.make('select');select.setAttribute('aria-label','Homepage text');Object.entries(textFields).forEach(([id,key])=>{const o=A.make('option',key);o.value=key;select.append(o);});edit.append(select);const renderText=key=>{fields.replaceChildren();A.field(fields,home(),key,{multiline:true});};select.onchange=()=>renderText(select.value);renderText('heroTitle');
    $('preview').addEventListener('load',()=>{try{const doc=$('preview').contentDocument;doc.addEventListener('click',e=>{if(!click.checked)return;const text=e.target.closest('[id]');if(text&&textFields[text.id]){e.preventDefault();e.stopPropagation();select.value=textFields[text.id];renderText(select.value);A.openStep('step8');return;}if(e.target.closest('img')){e.preventDefault();A.openStep(/logo/i.test(e.target.alt+' '+e.target.className+' '+e.target.id)?'step3':'step7');A.status('Image selected. Use the logo controls or project/photo manager to replace its source.');}},true);}catch{}});
    $('preview').addEventListener('load',()=>{try{$('preview').contentDocument.addEventListener('click',e=>{
      if(!click.checked||!e.target.closest('img'))return;
      const image=e.target.closest('img'),src=image.getAttribute('src');let match;
      const same=value=>{if(typeof value!=='string'||!value)return false;try{return new URL(A.assets.get(value)?.url||value,location.origin).href===new URL(src,location.origin).href;}catch{return false;}};
      const visit=obj=>{if(!obj||typeof obj!=='object')return;for(const [key,value] of Object.entries(obj)){if(same(value)){match={obj,key};return;}if(typeof value==='object')visit(value);if(match)return;}};
      visit(A.files());if(!match)return;fields.replaceChildren();A.field(fields,match.obj,match.key,{image:true,url:true,title:'Selected image source'});A.openStep('step8');A.status('Replace this image here; the draft keeps its original file until you choose a new one.');
    },true);}catch{}});
    const buttonFields=A.make('div');edit.append(buttonFields);const renderButtons=()=>{buttonFields.replaceChildren();for(const key of ['heroPrimaryButtonUrl','heroSecondaryButtonUrl'])A.field(buttonFields,home(),key,{title:key==='heroPrimaryButtonUrl'?'Main button destination (optional)':'Second button destination (optional)'});};renderButtons();
    edit.append(A.button('Use smart estimate for second homepage button',()=>A.mutate(()=>{home().heroSecondaryButtonUrl='/estimate-request.html';home().heroSecondaryButtonText='Plan your project';})));
    const mobile=panel('step9','9 · Mobile focus and section reset');para(mobile,'Choose a point in your background image. Cover preserves proportions and crops; contain shows the full image and may leave space.');const target=A.make('select');for(const x of ['Mobile','Desktop'])target.append(A.make('option',x));mobile.append(target);const img=A.make('img');img.style.cssText='width:100%;max-height:260px;object-fit:contain;cursor:crosshair';img.alt='Click to set background focal point';mobile.append(img);const refreshFocus=()=>{const path=target.value==='Mobile'?(design().backgroundMobile||design().backgroundDesktop):design().backgroundDesktop;img.src=A.assets.get(path)?.url||path||'';};target.onchange=refreshFocus;mobile.append(A.button('Load selected background',refreshFocus));img.onclick=e=>{const r=img.getBoundingClientRect(),scale=Math.min(r.width/img.naturalWidth,r.height/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale,x=Math.max(0,Math.min(100,(e.clientX-r.left-(r.width-w)/2)/w*100)),y=Math.max(0,Math.min(100,(e.clientY-r.top-(r.height-h)/2)/h*100));if(!Number.isFinite(x+y))return;A.mutate(()=>design()[target.value==='Mobile'?'backgroundMobilePosition':'backgroundPosition']=Math.round(x)+'% '+Math.round(y)+'%');};mobile.append(A.button('Reset selected section background',()=>{const token=$('sectionBackgroundSelect').value;A.mutate(()=>{const row=design().sectionBackgrounds.find(x=>x.section===token),original=A.original()[DESIGN].sectionBackgrounds?.find(x=>x.section===token);Object.assign(row,original||{enabled:false,desktopImage:'',mobileImage:'',color:''});});}));
    const story=panel('step10','10 · Build a real job story');para(story,'Select a project under section 7. Enter facts you can verify, then prepare its page, before/after feature and social draft. Rebuild after changing its status or details.');const storyFields=A.make('div');story.append(storyFields);function renderStory(){storyFields.replaceChildren();const p=project();if(!p)return;for(const key of ['storyProblem','storySolution','storyResult','beforeAlt','afterAlt'])A.field(storyFields,p,key,{multiline:true});const l=A.make('label',' These are genuine project photos and accurate work details'),c=A.make('input');c.type='checkbox';c.checked=p.realProjectConfirmed===true;c.onchange=()=>A.mutate(()=>p.realProjectConfirmed=c.checked);l.prepend(c);storyFields.append(l);}story.append(A.button('Load selected project',()=>{renderStory();renderPhotoOrder();}),A.button('Prepare project page + social draft',generateStory));const photos=A.make('div');photos.id='photoOrder';story.append(photos);renderStory();renderPhotoOrder();$('projectSelect').addEventListener('change',()=>{renderStory();renderPhotoOrder();});
    const comparison=panel('step11','11 · Before-and-after storytelling');para(comparison,'Choose a comparison in section 7, then load its story controls.');const pairFields=A.make('div');comparison.append(pairFields,A.button('Load selected comparison',()=>{pairFields.replaceChildren();const p=A.files()['gallery.json'].homePairs[A.selectedPair()];if(!p)return;A.field(pairFields,p,'summary',{multiline:true});if(p.sliderStart===undefined)p.sliderStart=50;A.field(pairFields,p,'sliderStart',{min:0,max:100,title:'Starting slider position (%)'});}));
    const campaign=panel('step12','12 · Campaign presets');para(campaign,'Save your current design, wording, section order and featured-item choices. Applying a campaign is manual; it never switches by date.');const name=input(campaign,'Campaign name','Roofing season'),list=A.make('select');campaign.append(list);const refresh=()=>{list.replaceChildren();Object.keys(storage(CAMPAIGNS,{})).forEach(n=>list.append(A.make('option',n)));};refresh();campaign.append(A.button('Save campaign',()=>{if(!name.value.trim())return A.status('Name your campaign.');const all=storage(CAMPAIGNS,{});if(all[name.value]&&!confirm('Replace this campaign?'))return;all[name.value]={home:clone(home()),design:clone(design()),projects:A.files()[PROJECTS].projects.map(p=>({slug:p.slug,title:p.title,featured:p.featured,showOnHomepage:p.showOnHomepage,displayOrder:p.displayOrder})),reviews:A.files()['site-data/reviews.json'].reviews.map(p=>({name:p.name,text:p.text,featured:p.featured,showOnHomepage:p.showOnHomepage,displayOrder:p.displayOrder}))};try{localStorage.setItem(CAMPAIGNS,JSON.stringify(all));refresh();A.status('Campaign saved on this device.');}catch{A.status('Device storage is full. Export a backup.');}}),A.button('Apply campaign to draft',()=>{const c=storage(CAMPAIGNS,{})[list.value];if(!c)return;A.mutate(()=>{Object.assign(home(),clone(c.home));Object.assign(design(),clone(c.design));for(const [path,key,saved] of [[PROJECTS,'projects',c.projects],['site-data/reviews.json','reviews',c.reviews]])for(const item of A.files()[path][key]){const match=saved.find(x=>key==='projects'?(x.slug&&x.slug===item.slug)||(x.title&&x.title===item.title):x.name===item.name&&x.text===item.text);if(match)for(const prop of ['featured','showOnHomepage','displayOrder'])if(match[prop]!==undefined)item[prop]=match[prop];}});}));
    const intake=panel('step13','13 · Smart estimate requests');para(intake,'The new /estimate-request.html asks service-specific questions and prepares a text message. To accept online submissions and photo uploads, supply your own HTTPS form-service endpoint. No endpoint means no online collection.');A.field(intake,home(),'estimateFormEndpoint',{title:'Form-service HTTPS endpoint (optional)'});intake.append(A.button('Preview estimate page',()=>window.open('/estimate-request.html','_blank','noopener')));
    const safety=panel('step14','14 · Draft recovery, upload checks and one ZIP');const recovery=storage(KEY,null);para(safety,recovery?'A saved draft is available from '+recovery.savedAt+'.':'Drafts save on this device while you work. Keep a downloaded backup as well.');safety.append(A.button('Recover last saved draft',async()=>{try{if(!recovery)return A.status('No earlier draft found.');await restore(recovery);}catch(e){A.status(e.message);}}),A.button('Download backup including images',async()=>{try{A.download('HammerBrick-Control-3-Backup.json',await bundle());}catch(e){A.status(e.message);}}));const imp=input(safety,'Import Control 3 backup');imp.type='file';imp.accept='.json,.txt';imp.onchange=async()=>{try{await restore(JSON.parse(await imp.files[0].text()));}catch(e){A.status(e.message);}};
    safety.append(A.button('Check local links and images',audit));const result=A.make('pre');result.id='auditResults';result.style.whiteSpace='pre-wrap';safety.append(result,A.button('Download ONE ZIP with changed files',exportZip));
    $('downloadAll').onclick=exportZip;$('downloadAll').textContent='Download one ZIP of changed files';$('backup').textContent='Download settings-only backup (V2)';
    const summary=A.make('pre');summary.style.cssText='white-space:pre-wrap;font-size:12px';safety.append(summary);
    let last=JSON.stringify(A.files())+JSON.stringify([...generated]),saving=false;setInterval(async()=>{const current=JSON.stringify(A.files())+JSON.stringify([...generated]);summary.textContent=diff();if(current===last||saving)return;saving=true;try{const b=await bundle();localStorage.setItem(KEY,JSON.stringify(b));last=current;}catch{A.status('Draft could not be saved on this device. Download a backup with images.');}finally{saving=false;}},1800);
    window.addEventListener('beforeunload',e=>{if(A.changedPaths().length||generated.size||A.assets.size){e.preventDefault();e.returnValue='';}});
    window.addEventListener('hammer-draft-changed',()=>{renderText(select.value);renderStory();renderPhotoOrder();renderButtons();pairFields.replaceChildren();const endpointLabel=intake.querySelector('label');if(endpointLabel)endpointLabel.remove();A.field(intake,home(),'estimateFormEndpoint',{title:'Form-service HTTPS endpoint (optional)'});});
    window.HammerControl3={zip,crc,buildStory,restore,bundle,generated,audit,exportZip};
    A.status('Control 3 ready. Your current design and existing controls are preserved.');
  }
  init();
})();
