/* Owner Workshop 4: local-first tools, manual downloads, no account tokens or writes. */
(() => {
  'use strict';
  const W = window.HammerWorkshop, $ = id => document.getElementById(id);
  const BASE = 'https://www.hammerbrickhome.com', CONFIG = 'site-data/owner-tools.json';
  const PATHS = [CONFIG,'site-data/homepage.json','site-data/design.json','site-data/projects.json','site-data/reviews.json','site-data/pages.json','site-data/business.json','site-data/seo.json','gallery.json'];
  const files = {}, original = {}, assets = new Map(), generated = new Map(), documents = new Map(), localFiles = new Map();
  let config, projectIndex=0, projectDraft=null, photo=null, photoVariants=[], photoHashes=new Set(), vault=[], vaultDirty=false, lastPrint='', ready=false;
  let inspectReport=null, wallReport=null, healthReport=null;
  const previewAssets = new Map();
  const devices=[['Small iPhone',375,667],['iPhone Pro Max',430,932],['Android',412,915],['Tablet',768,1024],['Laptop',1366,900],['Desktop',1920,1080]];
  const business=()=>files['site-data/business.json']||{}, projects=()=>files['site-data/projects.json'].projects;
  const make=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
  const status=msg=>{$('status').textContent=msg;};
  const issue=(level,path,message)=>({level,path,message});
  const button=(label,fn)=>{const n=make('button',label);n.type='button';n.onclick=()=>Promise.resolve().then(fn).catch(e=>status(e.message));return n;};
  function download(name,value,type='application/json') { const blob=value instanceof Blob?value:new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)+'\n'],{type});const url=URL.createObjectURL(blob),a=make('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000); }
  const json=async path=>{const r=await fetch('/'+path,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Unable to load '+path+' (HTTP '+r.status+').');return r.json();};
  const textFile=async path=>{if(localFiles.size){const f=localFiles.get(path);if(!f)throw Error('Missing local file '+path);return f.text();}const r=await fetch('/'+path,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('HTTP '+r.status+' for '+path);return r.text();};
  const changedPaths=()=>PATHS.filter(p=>JSON.stringify(files[p])!==JSON.stringify(original[p]));
  function refreshExport(){if(!ready)return;const paths=[...changedPaths(),...generated.keys(),...assets.keys()];$('changeSummary').textContent=paths.length?paths.length+' website files prepared. Nothing has been uploaded.':'No website changes. Opening tools does not change your site.';$('fileList').textContent=paths.join('\n')||'Private vault and reports are never included in website exports.';$('downloadPackage').disabled=!paths.length&&!documents.size;}
  function remember(){refreshExport();status('Workshop draft updated. Upload only when you choose.');}
  function resultList(root,rows){root.replaceChildren();for(const r of rows){const d=make('div');d.className='result '+r.level;d.append(make('b',r.level.toUpperCase()+' · '+(r.path||'')),make('div',r.message));root.append(d);}}
  function on(id,event,fn){$(id).addEventListener(event,async e=>{try{if(!ready)throw Error('Wait for the current website files to load.');await fn(e);}catch(err){status(err.message);}});}
  function bindValue(id,obj,key,type='text'){const n=$(id);if(type==='check')n.checked=!!obj[key];else n.value=obj[key]??'';n.onchange=()=>{obj[key]=type==='check'?n.checked:n.value;remember();};}
  function publicSettings(){const clean=W.clone(config);clean.publicTrust=(config.publicTrust||[]).map(r=>({label:r.label,number:r.number,validUntil:r.validUntil,ownerVerified:r.ownerVerified===true}));return clean;}
  function previewUrl(){
    for(const [p,blob] of assets)if(!previewAssets.has(p))previewAssets.set(p,URL.createObjectURL(blob));
    const replace=v=>Array.isArray(v)?v.map(replace):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,replace(x)])):typeof v==='string'&&previewAssets.has(v.replace(/^\//,''))?previewAssets.get(v.replace(/^\//,'')):v;
    sessionStorage.setItem('hammer-studio-preview-v2',JSON.stringify({format:'hammer-visual-control-v2',files:replace(files)}));return '/?studioPreview=2&workshop='+Date.now();
  }
  function initControls(){
    bindValue('chooserEnabled',config,'projectChooserEnabled','check');bindValue('chooserHeading',config,'projectChooserHeading');$('chooserCategories').value=config.projectChooserCategories.join('\n');on('chooserCategories','change',()=>{config.projectChooserCategories=[...new Set($('chooserCategories').value.split('\n').map(s=>s.trim()).filter(Boolean))];remember();});
    bindValue('publicTrustEnabled',config,'publicTrustEnabled','check');renderTrustSummary();
    for(const [id,key,type] of [['membershipOverride','overrideEnabled','check'],['membershipActivated','activated','check'],['membershipHide','hideUntilActivated','check'],['membershipStatus','status'],['membershipYear','year']])bindValue(id,config.membership,key,type);
    for(const [id,key,type] of [['emergencyEnabled','enabled','check'],['emergencyTitle','title'],['emergencyMessage','message'],['emergencyLinkText','linkText'],['emergencyLinkUrl','linkUrl'],['emergencyAutoExpire','autoExpire','check']])bindValue(id,config.emergency,key,type);
    if(config.emergency.expiresAt){const d=new Date(config.emergency.expiresAt);if(!isNaN(d))$('emergencyExpiry').value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
    on('emergencyExpiry','change',()=>{const value=$('emergencyExpiry').value;config.emergency.expiresAt=value?new Date(value).toISOString():'';remember();});
    on('emergencyPreset','change',()=>{if(!$('emergencyPreset').value)return;config.emergency.title=$('emergencyPreset').value;config.emergency.message=config.emergency.title==='Fully booked'?'Our current schedule is full. Please check with us about future availability.':'Explore our '+config.emergency.title.toLowerCase()+' service information. Availability and site conditions must be confirmed.';$('emergencyTitle').value=config.emergency.title;$('emergencyMessage').value=config.emergency.message;remember();});
    $('printLogo').value=files['site-data/design.json'].logoDesktop||files['site-data/design.json'].heroLogo||'';
    renderProjectSelect();
    $('searchPage').replaceChildren();
    for(const p of files['site-data/pages.json'].pages||[]){if(!p.url||!W.safeUrl(p.url))continue;const o=make('option',p.menuLabel||p.slug||p.url);o.value=p.url;$('searchPage').append(o);}
  }
  async function loadPhoto(file){
    if(!file||!/^image\/(jpeg|png|webp|avif)$/.test(file.type))throw Error('Choose a JPEG, PNG, WebP or AVIF photograph.');
    if(file.size>24*1024*1024)throw Error('Choose a photo under 24 MB.');
    const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())),v=>v.toString(16).padStart(2,'0')).join('');
    const duplicate=photoHashes.has(hash)||config.photoManifest.some(r=>r.sourceHash===hash);photoHashes.add(hash);
    const url=URL.createObjectURL(file),img=new Image();img.src=url;try{await img.decode();}catch{URL.revokeObjectURL(url);throw Error('This browser could not decode that photo. Try JPEG or PNG.');}
    if(img.naturalWidth*img.naturalHeight>50000000){URL.revokeObjectURL(url);throw Error('Photo exceeds 50 megapixels; resize it before loading.');}
    if(photo)URL.revokeObjectURL(photo.url);photoVariants.forEach(p=>URL.revokeObjectURL(p.url));photoVariants=[];photo={file,hash,img,url};$('photoName').value=W.slug(file.name.replace(/\.[^.]+$/,''));$('photoOutputs').replaceChildren();renderPhoto();
    const flags=[];if(duplicate)flags.push('Duplicate source already prepared in this session or manifest.');if(file.size>2*1024*1024)flags.push('Large original; use optimized outputs on the website.');if(img.naturalWidth<1200)flags.push('Limited source width; desktop output will not be enlarged.');
    const sample=document.createElement('canvas');sample.width=128;sample.height=128;const ctx=sample.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,128,128);const pix=ctx.getImageData(0,0,128,128).data;let edge=0;for(let i=4;i<pix.length;i+=4)edge+=Math.abs(pix[i]-pix[i-4]);if(edge/(pix.length/4)<5)flags.push('Low-detail / possible blur warning. Inspect visually; smooth scenes can trigger this.');
    $('photoInfo').textContent=img.naturalWidth+' × '+img.naturalHeight+' · '+(file.size/1048576).toFixed(2)+' MB\n'+(flags.join('\n')||'Source ready.');
  }
  function renderPhoto(){if(!photo)return;const c=$('photoCanvas'),ratio=photo.img.naturalWidth/photo.img.naturalHeight;c.width=600;c.height=Math.round(600/ratio);const ctx=c.getContext('2d');ctx.drawImage(photo.img,0,0,c.width,c.height);const x=+$('focusX').value/100*c.width,y=+$('focusY').value/100*c.height;ctx.beginPath();ctx.arc(x,y,10,0,Math.PI*2);ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.arc(x,y,14,0,Math.PI*2);ctx.strokeStyle='#142e26';ctx.stroke();}
  async function preparePhotos(){
    if(!photo)throw Error('Choose a photograph first.');const description=$('photoDescription').value.trim(),name=W.slug($('photoName').value||description);if(!name||!description)throw Error('Add a filename and an accurate photo description.');photoVariants.forEach(p=>URL.revokeObjectURL(p.url));photoVariants=[];
    const specs=[['desktop',photo.img.naturalWidth/photo.img.naturalHeight,1920],['mobile',4/5,768],['square',1,1000],['four-three',4/3,1600],['sixteen-nine',16/9,1600]];
    for(const [kind,ratio,max] of specs){const rect=W.cropRect(photo.img.naturalWidth,photo.img.naturalHeight,ratio,$('focusX').value,$('focusY').value),size=W.outputSize(rect,max),c=document.createElement('canvas');c.width=size.width;c.height=size.height;c.getContext('2d').drawImage(photo.img,rect.sx,rect.sy,rect.sw,rect.sh,0,0,size.width,size.height);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/webp',+$('photoQuality').value/100));if(!blob)throw Error('Photo encoding failed.');const ext=blob.type==='image/webp'?'webp':'png',path='images/owner/'+name+'-'+photo.hash.slice(0,8)+'-x'+$('focusX').value+'y'+$('focusY').value+'q'+$('photoQuality').value+'-'+kind+'.'+ext;photoVariants.push({kind,path,blob,url:URL.createObjectURL(blob),width:size.width,height:size.height,alt:description,sourceHash:photo.hash});}
    $('photoOutputs').replaceChildren();for(const p of photoVariants){const tile=make('div');tile.className='tile';const img=make('img');img.src=p.url;img.alt=p.alt;tile.append(img,make('b',p.kind),make('small',p.width+' × '+p.height+' · '+Math.round(p.blob.size/1024)+' KB'),button('Download',()=>download(p.path.split('/').pop(),p.blob)));$('photoOutputs').append(tile);}status('Five proportional variants prepared. Check the crops before adding them.');
  }
  function addPhotos(){if(!photoVariants.length)throw Error('Prepare photographs first.');for(const p of photoVariants){assets.set(p.path,p.blob);const record={path:'/'+p.path,width:p.width,height:p.height,alt:p.alt,kind:p.kind,sourceHash:p.sourceHash,bytes:p.blob.size};const i=config.photoManifest.findIndex(r=>r.path===record.path);if(i<0)config.photoManifest.push(record);else config.photoManifest[i]=record;}
    if($('photoUse').value==='background'){const d=files['site-data/design.json'];Object.assign(d,{backgroundEnabled:true,backgroundDesktop:'/'+photoVariants[0].path,backgroundMobile:'/'+photoVariants[1].path,backgroundSize:'cover',backgroundSizeMobile:'cover',backgroundPosition:'center center',backgroundMobilePosition:'center center'});}
    if($('photoUse').value==='project'){if(!projectDraft)throw Error('Select or create a project first.');projectDraft.coverImage='/'+photoVariants[0].path;projectDraft.imageAlt=photoVariants[0].alt;saveProject();renderProject();}remember();}
  function renderProjectSelect(){const select=$('projectSelect');select.replaceChildren();projects().forEach((p,i)=>{const o=make('option',p.title||'Untitled existing project '+(i+1));o.value=i;select.append(o);});projectIndex=Math.min(projectIndex,Math.max(0,projects().length-1));select.value=projectIndex;projectDraft=projects()[projectIndex]?W.clone(projects()[projectIndex]):null;renderProject();}
  function renderProject(){const root=$('projectFields');root.replaceChildren();if(!projectDraft)return;const fields={title:'Project title',slug:'Short URL name',serviceLabel:'Service',areaLabel:'Borough / service area',neighborhood:'Public neighborhood (not customer address)',summary:'Summary',coverImage:'Cover photo path',imageAlt:'Cover photo description',beforeImage:'Before photo path',beforeAlt:'Before photo description',afterImage:'After photo path',afterAlt:'After photo description',storyProblem:'Original problem',storySolution:'Work performed',storyResult:'Finished result',materialsUsed:'Actual materials',timeline:'Actual timeline',careInstructions:'Project-specific care instructions',warrantyTerms:'Exact written warranty terms (optional)'};
    for(const [key,label] of Object.entries(fields)){const l=make('label',label),input=make(/summary|story|Instructions|Terms|materialsUsed/.test(key)?'textarea':'input');input.value=projectDraft[key]||'';input.id='project-'+key;input.oninput=()=>projectDraft[key]=input.value;l.append(input);root.append(l);}
    const label=make('label','Publication status'),select=make('select');for(const value of ['draft','live','archived']){const o=make('option',value);o.value=value;select.append(o);}select.value=['draft','live','archived'].includes(projectDraft.publishStatus)?projectDraft.publishStatus:'draft';select.id='project-publishStatus';select.onchange=()=>{projectDraft.publishStatus=select.value;projectDraft.active=select.value==='live';};label.append(select);root.append(label);$('projectConfirmed').checked=projectDraft.realProjectConfirmed===true;
    $('projectConfirmed').onchange=()=>projectDraft.realProjectConfirmed=$('projectConfirmed').checked;
  }
  function saveProject(){if(!projectDraft)throw Error('Select a project first.');projects()[projectIndex]=W.clone(projectDraft);const option=$('projectSelect').options[projectIndex];if(option)option.textContent=projectDraft.title||'Untitled project';remember();}
  function printable(title,body,options={}){const b=business(),logo=$('printLogo').value.trim(),url=options.url||$('printUrl').value.trim()||BASE+'/';if(!W.safeUrl(url))throw Error('Use a valid HTTPS or local QR destination.');const dest=new URL(url,BASE).href;const width=W.clamp($('printWidth').value,2,100),height=W.clamp($('printHeight').value,2,100);return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>'+W.esc(title)+'</title><style>'+W.printStyle()+'@page{size:'+width+'in '+height+'in;margin:.4in}</style></head><body><header>'+(W.safeUrl(logo)?'<img class="logo" src="'+W.esc(new URL(logo,BASE).href)+'" alt="'+W.esc(b.businessName)+' logo">':'')+'<p class="brand">'+W.esc(b.businessName)+'</p></header><main class="sheet"><h1>'+W.esc(title)+'</h1>'+body+'<section>'+W.qrSvg(dest)+'<p>'+W.esc(dest)+'</p></section></main><footer>'+W.esc(b.phone)+' · '+W.esc(b.website||BASE)+'</footer></body></html>';}
  function setDocument(name,text){documents.set(name,text);}
  async function inlinePreparedImages(html){
    const doc=new DOMParser().parseFromString(html,'text/html');
    for(const img of doc.images){const u=new URL(img.getAttribute('src'),BASE);const blob=assets.get(decodeURIComponent(u.pathname).replace(/^\//,''));if(u.origin===BASE&&blob)img.src='data:'+blob.type+';base64,'+encode64(new Uint8Array(await blob.arrayBuffer()));else if(u.protocol==='https:')img.src=u.href;}
    return '<!doctype html>\n'+doc.documentElement.outerHTML;
  }
  async function prepareProject(){
    if(!projectDraft)throw Error('Choose a project first.');const p=W.clone(projectDraft),pack=W.projectPack(p,business());
    W.qrSvg(pack.url); // Validate QR capacity before staging any website changes.
    // Avoid replacing an existing live story without an explicit confirmation.
    if((generated.has(pack.path)||(files['site-data/pages.json'].pages||[]).some(r=>r.url==='/'+pack.path))&&!confirm('Replace the prepared story at '+pack.path+'?'))return;
    let sitemap=generated.get('sitemap.xml');if(!sitemap)sitemap=await textFile('sitemap.xml');const doc=new DOMParser().parseFromString(sitemap,'application/xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='urlset')throw Error('Cannot safely update sitemap.xml; repair it first.');
    const ns=doc.documentElement.namespaceURI||'http://www.sitemaps.org/schemas/sitemap/0.9';for(const row of [...doc.getElementsByTagNameNS('*','url')])if(row.getElementsByTagNameNS('*','loc')[0]?.textContent===pack.url)row.remove();if(pack.live){const row=doc.createElementNS(ns,'url'),loc=doc.createElementNS(ns,'loc');loc.textContent=pack.url;row.append(loc);doc.documentElement.append(row);}
    generated.set(pack.path,pack.html);generated.set('sitemap.xml',new XMLSerializer().serializeToString(doc));
    Object.assign(p,{ctaUrl:'/'+pack.path,ctaText:'Read the project story'});projects()[projectIndex]=p;projectDraft=W.clone(p);
    const items=files['site-data/pages.json'].pages,row={slug:pack.path.replace('.html',''),url:'/'+pack.path,menuLabel:p.title,seoTitle:p.seoTitle||p.title,seoDescription:p.seoDescription||p.summary,socialImage:p.coverImage,active:pack.live,allowIndexing:pack.live,showInSitemap:pack.live,structuredDataType:'page'},i=items.findIndex(x=>x.url===row.url);if(i<0)items.push(row);else items[i]={...items[i],...row};
    if(W.safeUrl(p.beforeImage)&&W.safeUrl(p.afterImage)){const pairs=files['gallery.json'].homePairs,pair={label:p.title,before:p.beforeImage,after:p.afterImage,beforeAlt:p.beforeAlt||'Before: '+p.imageAlt,afterAlt:p.afterAlt||'After: '+p.imageAlt,active:pack.live,storyUrl:row.url,tags:[p.serviceLabel,p.areaLabel].filter(Boolean)},at=pairs.findIndex(x=>x.storyUrl===row.url);if(at<0)pairs.push(pair);else pairs[at]={...pairs[at],...pair};}
    const prefix=W.slug(p.title);setDocument(prefix+'-google-post.txt',pack.caption+'\n\nDRAFT: review facts and Google Business Profile policies before posting.');setDocument(prefix+'-social-caption.txt',pack.caption);setDocument(prefix+'-project-sheet.html',await inlinePreparedImages(printable(p.title,pack.body,{url:pack.url})));setDocument(prefix+'-care-sheet.html',await inlinePreparedImages(printable('Care for '+p.title,'<p>'+W.esc(pack.care)+'</p>'+(p.warrantyTerms?'<h2>Written warranty terms</h2><p>'+W.esc(p.warrantyTerms)+'</p>':''),{url:pack.url})));setDocument(prefix+'-qr.svg',W.qrSvg(pack.url));setDocument(prefix+'-image-metadata.json',JSON.stringify({title:p.title,cover:{path:p.coverImage,alt:p.imageAlt},before:{path:p.beforeImage,alt:p.beforeAlt},after:{path:p.afterImage,alt:p.afterAlt},note:'Descriptions are owner-entered; verify every photograph.'},null,2));
    $('projectResult').textContent='Prepared '+pack.path+'\nStatus: '+(pack.live?'LIVE after you upload':'DRAFT / noindex after upload')+'\nSitemap registration: '+(pack.live?'included':'excluded')+'\nUpload folder: website files only.\nOWNER-DOCUMENTS folder: captions, print sheets, metadata and QR. Not for GitHub.';$('projectDocuments').replaceChildren();for(const [name,value] of documents)if(name.startsWith(prefix))$('projectDocuments').append(button(name,()=>download(name,value,name.endsWith('.html')?'text/html':'text/plain')));remember();
  }

  function encode64(bytes){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);}
  function decode64(s){if(typeof s!=='string'||s.length>60000000)throw Error('Invalid encrypted vault.');return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
  async function vaultKey(pass,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
  async function encryptVault(records,pass){if(pass.length<12)throw Error('Use a passphrase of at least 12 characters.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await vaultKey(pass,salt),bytes=new TextEncoder().encode(JSON.stringify({version:1,records})),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,bytes);return {format:'hammer-private-vault-1',kdf:'PBKDF2-SHA256',iterations:310000,cipher:'AES-256-GCM',salt:encode64(salt),iv:encode64(iv),ciphertext:encode64(new Uint8Array(cipher))};}
  async function decryptVault(data,pass){if(data?.format!=='hammer-private-vault-1'||data.iterations!==310000)throw Error('Unsupported vault format.');try{const salt=decode64(data.salt),iv=decode64(data.iv);if(salt.length!==16||iv.length!==12)throw Error('Invalid key parameters');const key=await vaultKey(pass,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,decode64(data.ciphertext)),value=JSON.parse(new TextDecoder().decode(plain));if(value.version!==1||!Array.isArray(value.records)||value.records.length>100)throw Error('Invalid records');for(const r of value.records)if(!r||typeof r.label!=='string'||(r.document&&!/^data:(application\/pdf|image\/(jpeg|png));base64,/.test(r.document.data)))throw Error('Invalid record');return value.records;}catch{throw Error('Cannot open the vault. Check the passphrase and file integrity.');}}
  async function addCertificate(){const label=$('certLabel').value.trim()||$('certType').value;if(!$('certExpiry').value)throw Error('Add the document expiration date.');let attachment=null;const file=$('certDocument').files[0];if(file){if(file.size>8*1024*1024||!['application/pdf','image/png','image/jpeg'].includes(file.type))throw Error('Supporting documents must be a PDF, PNG or JPEG under 8 MB.');attachment={name:file.name,type:file.type,data:'data:'+file.type+';base64,'+encode64(new Uint8Array(await file.arrayBuffer()))};}
    vault.push({id:crypto.randomUUID(),type:$('certType').value,label,number:$('certNumber').value,expiry:$('certExpiry').value,notes:$('certNotes').value,verified:$('certVerified').checked,public:$('certPublic').checked,document:attachment});vaultDirty=true;renderVault();$('certDocument').value='';status('Private record added in memory. Download an encrypted vault before closing.');}
  function renderVault(){$('certList').replaceChildren();vault.forEach((r,i)=>{const state=W.certificateStatus(r),div=make('div');div.className='result '+(['expired','unverified'].includes(state)?'fail':state==='expires soon'?'warn':'pass');div.append(make('b',r.label+' · '+state.toUpperCase()),make('p',r.expiry+' · '+(r.public?'Public summary approved':'Private only')));if(r.document)div.append(button('Download supporting document',()=>{const raw=r.document.data.split(',')[1];download(r.document.name,new Blob([decode64(raw)],{type:r.document.type}));}));div.append(button('Remove record',()=>{if(confirm('Remove this record from memory? Your earlier encrypted backups are unchanged.')){vault.splice(i,1);vaultDirty=true;renderVault();}}));$('certList').append(div);});if(!vault.length)$('certList').append(make('p','Vault locked or empty. Open an encrypted file or add a record.'));}
  function renderTrustSummary(){$('trustSummary').textContent=config.publicTrust.length+' public summaries in this website draft. Only labels, public numbers and valid-until dates are exported.';}
  function buildPrint(){const type=$('printType').value,title=$('printHeading').value.trim()||'Hammer Brick & Home',body=$('printBody').value,p=projectDraft;let content='<p>'+W.esc(body)+'</p>';
    if(['project','commercial','capability'].includes(type)&&p?.title)content+='<h2>'+W.esc(p.title)+'</h2><p>'+W.esc(p.summary||'')+'</p>'+(W.safeUrl(p.coverImage)?'<img src="'+W.esc(new URL(p.coverImage,BASE).href)+'" alt="'+W.esc(p.imageAlt||p.title)+'">':'');
    if(type==='beforeafter'){if(!p||!W.safeUrl(p.beforeImage)||!W.safeUrl(p.afterImage))throw Error('Choose a project with before and after photographs.');content+='<div class="pair"><figure><img src="'+W.esc(new URL(p.beforeImage,BASE).href)+'" alt="'+W.esc(p.beforeAlt||'Before')+'"><figcaption>Before</figcaption></figure><figure><img src="'+W.esc(new URL(p.afterImage,BASE).href)+'" alt="'+W.esc(p.afterAlt||'After')+'"><figcaption>After</figcaption></figure></div>';}
    if(type==='credentials'){const approved=W.publicCertificates(vault);if(!approved.length)throw Error('Add and verify public-approved unexpired records in the vault first.');content+='<ul>'+approved.map(r=>'<li>'+W.esc(r.label)+' '+W.esc(r.number)+' · valid through '+W.esc(r.validUntil)+'</li>').join('')+'</ul><p>Owner-entered summary. Supporting documents and scope are available for verification.</p>';}
    if(type==='care')content+='<h2>Care instructions</h2><p>'+W.esc(p?.careInstructions||'Enter project-specific care instructions above.')+'</p>'+(p?.warrantyTerms?'<h2>Written warranty</h2><p>'+W.esc(p.warrantyTerms)+'</p>':'');
    return printable(title,content);
  }

  function scanDocument(html,path){const doc=new DOMParser().parseFromString(html,'text/html'),rows=[],meta=name=>doc.querySelector('meta[name="'+name+'"]')?.content||'';const fragment=!/<html\b/i.test(html);const title=doc.title.trim(),desc=meta('description'),canonical=doc.querySelector('link[rel="canonical"]')?.getAttribute('href')||'',noindex=/noindex/i.test(meta('robots'));if(!title&&!fragment)rows.push(issue('fail',path,'Missing title.'));else if(title&&(title.length>65||title.length<15))rows.push(issue('warn',path,'Title length '+title.length+'; review clarity, not a ranking score.'));if(!desc&&!fragment)rows.push(issue('warn',path,'No meta description.'));if(!canonical&&!fragment)rows.push(issue('warn',path,'No canonical URL.'));else if(!W.safeUrl(canonical)||!canonical.startsWith('https://'))rows.push(issue('fail',path,'Canonical must be a valid absolute HTTPS URL.'));if(noindex&&!path.startsWith('admin/'))rows.push(issue('warn',path,'noindex: confirm this page should be excluded.'));
    const schemas=[];for(const script of doc.querySelectorAll('script[type="application/ld+json"]')){try{const value=JSON.parse(script.textContent);const visit=v=>{if(Array.isArray(v))v.forEach(visit);else if(v&&typeof v==='object'){if(v['@type'])schemas.push(v);Object.values(v).forEach(visit);}};visit(value);}catch{rows.push(issue('fail',path,'Invalid JSON-LD syntax.'));}}
    const types=new Set(schemas.flatMap(s=>[].concat(s['@type'])));if(types.has('FAQPage'))rows.push(issue('warn',path,'FAQ rich results were retired by Google; do not promise FAQ enhancements.'));if(types.has('Review')||types.has('AggregateRating'))rows.push(issue('warn',path,'Check self-serving reviews: reviews of your own local business are not eligible for Google review stars.'));if(types.has('Product')&&!/product|shop|store/i.test(path))rows.push(issue('warn',path,'Product markup on a service page needs a factual eligibility review.'));if(!types.size)rows.push(issue('info',path,'No structured data in source; dynamic markup needs rendered inspection.'));
    for(const s of schemas){if([].concat(s['@type']).some(t=>['Organization','LocalBusiness','HomeAndConstructionBusiness','GeneralContractor'].includes(t))){if(!s.name)rows.push(issue('warn',path,'Business identity missing name.'));if(s['@id']&&!String(s['@id']).startsWith(BASE))rows.push(issue('warn',path,'Business @id differs from the canonical site domain.'));}}
    const imgs=[...doc.querySelectorAll('img')].filter(i=>!i.closest('template'));const missing=imgs.filter(i=>!i.hasAttribute('alt')).length;if(missing)rows.push(issue('warn',path,missing+' images lack alt attributes.'));if(/PENDING ACTIVATION/.test(doc.body.textContent))rows.push(issue('warn',path,'Membership pending-activation wording needs owner review.'));if(/Workers[’' ]*Comp/i.test(doc.body.textContent))rows.push(issue('warn',path,'Verify the current Workers’ Comp claim against your documents.'));const links=[...doc.querySelectorAll('[src],link[href],a[href]')].filter(n=>!n.closest('template')).map(n=>n.getAttribute(n.hasAttribute('src')?'src':'href')).filter(Boolean);
    return {doc,rows,title,desc,canonical,noindex,types:[...types],links,images:imgs.length};}
  function internalPath(raw,page='index.html'){try{const u=new URL(raw,BASE+'/'+page);if(u.origin!==BASE||!['https:','http:'].includes(u.protocol))return null;let p=decodeURIComponent(u.pathname).replace(/^\//,'');if(!p||p.endsWith('/'))p+='index.html';return W.safePath(p)?p:null;}catch{return null;}}
  async function pool(items,limit,fn){let at=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(at<items.length){const i=at++;await fn(items[i],i);}}));}
  async function inspect(){
    $('runInspect').disabled=true;try{const rows=[],docs=[],refs=new Set(),date=new Date().toISOString();const paths=localFiles.size?[...localFiles.keys()].filter(p=>p.endsWith('.html')&&!p.startsWith('admin/')):[...new Set(['index.html',...(files['site-data/pages.json'].pages||[]).map(p=>internalPath(p.url)).filter(Boolean)])];
    if(!paths.length)throw Error('No website HTML files found. Select the full repository folder.');
    await pool(paths,4,async path=>{try{const html=generated.get(path)||await textFile(path),d=scanDocument(html,path);rows.push(...d.rows);docs.push({path,...d});for(const u of d.links){const p=internalPath(u,path);if(p)refs.add(p);}}catch(e){rows.push(issue('fail',path,e.message));}});
    const duplicates=new Map();for(const d of docs){if(duplicates.has(d.title))rows.push(issue('warn',d.path,'Duplicate title also used by '+duplicates.get(d.title)));else duplicates.set(d.title,d.path);}
    const jsonPaths=localFiles.size?[...localFiles.keys()].filter(p=>p.endsWith('.json')&&!p.includes('node_modules/')&&!/^(admin-tools|reference)\//.test(p)&&!p.split('/').pop().startsWith('_')):PATHS;await pool(jsonPaths,4,async path=>{try{const data=files[path]&&!localFiles.size?files[path]:JSON.parse(await textFile(path));if(path===CONFIG)W.validateConfig(data).forEach(e=>rows.push(issue('fail',path,e)));const visit=(v,key='')=>{if(Array.isArray(v))return v.forEach(x=>visit(x,key));if(v&&typeof v==='object'){if(v.active===false||['draft','archived'].includes(v.publishStatus))return;return Object.entries(v).forEach(([k,x])=>visit(x,k));}if(typeof v==='string'&&/(?:image|photo|logo|backgroundDesktop|backgroundMobile|before|after|file|url)$/i.test(key)){const img=W.imagePath(v),ref=internalPath(img||v);if(ref)refs.add(ref);}};visit(data);}catch(e){rows.push(issue('fail',path,'Invalid or unavailable JSON: '+e.message));}});
    try{const sitemap=generated.get('sitemap.xml')||await textFile('sitemap.xml'),xml=new DOMParser().parseFromString(sitemap,'application/xml');if(xml.querySelector('parsererror')||xml.documentElement.localName!=='urlset')rows.push(issue('fail','sitemap.xml','Invalid sitemap XML.'));else for(const n of xml.getElementsByTagNameNS('*','loc')){const p=internalPath(n.textContent);if(p)refs.add(p);const d=docs.find(d=>d.path===p);if(d?.noindex)rows.push(issue('fail',p,'noindex page appears in sitemap.'));}}catch(e){rows.push(issue('fail','sitemap.xml',e.message));}
    try{const robots=await textFile('robots.txt');if(/Disallow:\s*\/\s*$/mi.test(robots))rows.push(issue('warn','robots.txt','Root disallow found; review user-agent scope.'));if(!/sitemap:/i.test(robots))rows.push(issue('warn','robots.txt','No sitemap declaration.'));}catch(e){rows.push(issue('warn','robots.txt',e.message));}
    await pool([...refs],5,async path=>{if(assets.has(path)||generated.has(path))return;if(localFiles.size){if(!localFiles.has(path))rows.push(issue('fail',path,'Referenced local file is missing (check case and folder).'));return;}try{const r=await fetch('/'+path,{method:'HEAD',cache:'no-store',signal:AbortSignal.timeout(9000)});if(!r.ok)rows.push(issue('fail',path,'Referenced path returned HTTP '+r.status));}catch{rows.push(issue('warn',path,'Could not check path; network or server restriction.'));}});
    if(localFiles.size)for(const [path,f] of localFiles)if(/\.(png|jpe?g|webp)$/i.test(path)&&f.size>2*1048576)rows.push(issue('warn',path,'Large image: '+(f.size/1048576).toFixed(1)+' MB.'));
    const unknown=projects().filter(p=>!p.title||!p.realProjectConfirmed).length;if(unknown)rows.push(issue('warn','site-data/projects.json',unknown+' existing project(s) need titles or genuine-work confirmation before new stories are generated. Existing data was not removed.'));
    inspectReport={format:'hammer-workshop-inspection-1',createdAt:date,source:localFiles.size?'local repository':'website fetch',pages:docs.length,paths:refs.size,results:rows,limits:'Not a live Google indexing check, full security audit or guarantee that every interactive function works.'};const counts=['fail','warn','info'].map(k=>k.toUpperCase()+': '+rows.filter(r=>r.level===k).length);$('inspectSummary').textContent=docs.length+' pages / '+refs.size+' referenced paths · '+counts.join(' · ');resultList($('inspectResults'),rows);status('Inspection complete. Review failures and warnings; no files were changed.');}finally{$('runInspect').disabled=false;}}

  async function loadWall(){const url=previewUrl();$('deviceWall').replaceChildren();for(const [name,width,height] of devices){const box=make('div');box.className='device';box.append(make('b',name+' · '+width+'×'+height));const stage=make('div');stage.className='viewport';const frame=make('iframe');frame.title=name+' homepage preview';frame.setAttribute('sandbox','allow-scripts allow-same-origin');frame.dataset.width=width;frame.dataset.height=height;frame.width=width;frame.height=height;frame.style.width=width+'px';frame.style.height=height+'px';frame.src=url;stage.append(frame);box.append(stage);$('deviceWall').append(box);const resize=()=>{const scale=Math.min(1,stage.clientWidth/width);frame.style.transform='scale('+scale+')';stage.style.height=Math.min(height*scale,500)+'px';};new ResizeObserver(resize).observe(stage);resize();}status('Six draft views loaded. Wait for their photographs before checking layouts.');}
  function accessibleName(el){const ids=(el.getAttribute('aria-labelledby')||'').split(/\s+/).filter(Boolean);return el.getAttribute('aria-label')||ids.map(id=>el.ownerDocument.getElementById(id)?.textContent||'').join(' ')||[...(el.labels||[])].map(l=>l.textContent).join(' ')||el.textContent.trim()||el.getAttribute('title')||el.getAttribute('alt')||'';}
  function renderedChecks(doc,win){const rows=[],width=win.innerWidth;const visible=el=>{const s=win.getComputedStyle(el),r=el.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0;};if(doc.documentElement.scrollWidth>width+2)rows.push(issue('fail','viewport','Horizontal overflow: '+doc.documentElement.scrollWidth+' px at '+width+' px viewport.'));for(const el of [...doc.querySelectorAll('img')].filter(visible)){const r=el.getBoundingClientRect(),s=win.getComputedStyle(el);if(!el.complete)rows.push(issue('info',el.getAttribute('src'),'Image still loading or deferred.'));else if(!el.naturalWidth)rows.push(issue('fail',el.getAttribute('src'),'Broken image.'));if(!el.hasAttribute('alt'))rows.push(issue('warn',el.getAttribute('src'),'Missing alt attribute.'));if(el.naturalWidth&&s.objectFit==='fill'&&Math.abs((r.width/r.height)/(el.naturalWidth/el.naturalHeight)-1)>.1)rows.push(issue('warn',el.getAttribute('src'),'Possible stretched image; check explicit dimensions and object-fit.'));}
    const controls=[...doc.querySelectorAll('button,a[href],input:not([type=hidden]),select,textarea')].filter(visible);for(const el of controls){const r=el.getBoundingClientRect(),name=accessibleName(el);if(!name)rows.push(issue('warn',el.tagName,'Control needs an accessible name.'));if((el.tagName==='BUTTON'||/INPUT|SELECT/.test(el.tagName))&&(r.width<24||r.height<24))rows.push(issue('warn',name.slice(0,90),'Small touch target under 24 CSS pixels; review WCAG exceptions and spacing.'));}
    for(const el of [...doc.querySelectorAll('h1,h2,h3,p,label,button')].filter(visible).slice(0,250)){const s=win.getComputedStyle(el),rgb=v=>{const m=v.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);return m?m.slice(1).map(Number):null;},fg=rgb(s.color),bg=rgb(s.backgroundColor);if(!fg||!bg||s.backgroundImage!=='none')continue;const lum=a=>a.map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;}).reduce((v,x,i)=>v+x*[.2126,.7152,.0722][i],0);const a=lum(fg),b=lum(bg),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05),large=parseFloat(s.fontSize)>=24||(parseFloat(s.fontSize)>=18.66&&+s.fontWeight>=700);if(ratio<(large?3:4.5))rows.push(issue('warn',el.textContent.trim().slice(0,60),'Contrast '+ratio.toFixed(2)+':1 below '+(large?3:4.5)+':1 for this flat background.'));}
    if(!doc.documentElement.lang)rows.push(issue('warn','html','Missing page language.'));if(!rows.length)rows.push(issue('pass','layout','No issues found in this limited rendered check.'));return rows;}
  function checkWall(){const result=[];for(const frame of $('deviceWall').querySelectorAll('iframe')){try{if(frame.contentDocument.readyState!=='complete')throw Error('Still loading');result.push({device:frame.title,width:+frame.dataset.width,height:+frame.dataset.height,results:renderedChecks(frame.contentDocument,frame.contentWindow)});}catch(e){result.push({device:frame.title,results:[issue('warn','preview','Could not inspect: '+e.message)]});}}if(!result.length)throw Error('Load the six-size wall first.');wallReport={format:'hammer-workshop-layout-1',createdAt:new Date().toISOString(),devices:result,limits:'Responsive viewport emulation; not a real-device or full overlap test.'};$('wallReport').textContent=result.map(r=>r.device+'\n'+r.results.map(i=>'  '+i.level.toUpperCase()+': '+i.message).join('\n')).join('\n\n');status('Layout check finished. Visually review each preview as well.');}
  async function health(){const frame=$('healthFrame');frame.src=previewUrl();await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Homepage preview timed out.')),20000);frame.onload=()=>{clearTimeout(t);resolve();};});await new Promise(r=>setTimeout(r,1200));const win=frame.contentWindow,doc=frame.contentDocument,rows=renderedChecks(doc,win),nav=win.performance.getEntriesByType('navigation')[0];let lcp=null,cls=0;const observe=(type,cb)=>{try{const o=new win.PerformanceObserver(list=>list.getEntries().forEach(cb));o.observe({type,buffered:true});return o;}catch{return null;}};const l=observe('largest-contentful-paint',e=>lcp=e.startTime),c=observe('layout-shift',e=>{if(!e.hadRecentInput)cls+=e.value;});await new Promise(r=>setTimeout(r,700));l?.disconnect();c?.disconnect();const resources=win.performance.getEntriesByType('resource'),bytes=resources.reduce((n,r)=>n+(r.transferSize||0),0);healthReport={format:'hammer-workshop-health-1',createdAt:new Date().toISOString(),lab:{loadMs:nav?Math.round(nav.loadEventEnd):null,lcpMs:lcp===null?null:Math.round(lcp),clsObserved:+cls.toFixed(4),inp:null,transferredBytes:bytes,resourceCount:resources.length},results:rows,limits:'One local lab load; iframe timing differs from the top-level page. Cached/CORS resources may report zero bytes. CLS is observed shifts, not full field scoring. INP and field percentiles require real-user data. Accessibility checks are partial.'};$('healthResults').textContent=JSON.stringify(healthReport,null,2);status('Homepage lab checks complete. No field INP or Google indexing data was assumed.');}
  async function search(){const path=internalPath($('searchPage').value);if(!path)throw Error('Choose a safe internal page.');const html=generated.get(path)||await textFile(path),d=scanDocument(html,path),root=$('snippet');root.replaceChildren();root.append(make('small',d.canonical||BASE+'/'+path),make('h3',d.title||'Title missing'),make('p',d.desc||'Description missing'));const social=d.doc.querySelector('meta[property="og:image"]')?.content;if(W.safeUrl(social)){const img=make('img');img.src=social;img.alt='Social sharing image preview';root.append(img);}const rows=[...d.rows,issue('info','Detected schema',d.types.join(', ')||'None in raw source')];resultList($('searchResults'),rows);const links=$('searchLinks');links.replaceChildren();for(const [label,href] of [['Google Rich Results Test','https://search.google.com/test/rich-results?url='+encodeURIComponent(BASE+'/'+path)],['Schema validator','https://validator.schema.org/#url='+encodeURIComponent(BASE+'/'+path)],['Search Console','https://search.google.com/search-console']]){const a=make('a',label);a.href=href;a.target='_blank';a.rel='noopener';links.append(a);}status("Search preview prepared. This is not a guarantee of Google's actual appearance.");}

  async function exportPackage(){
    const errors=W.validateConfig(config);if(errors.length)throw Error(errors.join(' '));const entries=[],add=(p,t)=>entries.push([p,t]);
    // Generated project HTML must still match its approved content.
    for(const [path,html] of generated)if(/^project-.*\.html$/.test(path)){const p=projects().find(x=>x.ctaUrl==='/'+path);if(!p||W.projectPack(p,business()).html!==html)throw Error('Project changed. Rebuild '+path+' before exporting.');}
    for(const p of changedPaths()){const value=p===CONFIG?publicSettings():files[p],text=JSON.stringify(value,null,2)+'\n';add('UPLOAD/'+p,text);add('TEXT-COPIES/'+p+'.txt',text);}for(const [p,text] of generated){if(!W.safePath(p))throw Error('Unsafe generated path');add('UPLOAD/'+p,text);add('TEXT-COPIES/'+p+'.txt',text);}for(const [p,blob] of assets)add('UPLOAD/'+p,new Uint8Array(await blob.arrayBuffer()));for(const [p,text] of documents)add('OWNER-DOCUMENTS/'+p,text);
    const paths=[...changedPaths(),...generated.keys(),...assets.keys()];add('READ-ME-FIRST.txt','HAMMER BRICK OWNER WORKSHOP DRAFT\n\nUpload ONLY the CONTENTS of UPLOAD to your repository root, keeping subfolders.\nDo not upload this outer folder, TEXT-COPIES, OWNER-DOCUMENTS or private vault files.\nText copies contain the same bytes with .txt appended. Remove only the final .txt if using them.\n\nFILES TO UPLOAD:\n'+paths.join('\n')+'\n\nOpening this editor made no public changes. Uploading to a repository connected to hosting can publish. Review the draft first.\nPRIVATE VAULT IS NOT IN THIS ZIP.\nDo not overwrite concurrent CMS edits: reload the latest site before beginning each edit batch.\n');if(!paths.length&&!documents.size)throw Error('No changes to export.');download('HammerBrick-Workshop-Draft.zip',W.zip(entries));status('One ZIP downloaded. Website files and owner-only documents are separated.');
  }
  async function publicBackup(){const out={format:'hammer-workshop-public-1',savedAt:new Date().toISOString(),files:W.clone(files),generated:Object.fromEntries(generated),documents:Object.fromEntries(documents),assets:[]};for(const [path,blob] of assets)out.assets.push({path,type:blob.type,data:encode64(new Uint8Array(await blob.arrayBuffer()))});out.files[CONFIG]=publicSettings();download('HammerBrick-Workshop-Public-Draft.json',out);}
  function validateBackup(b){if(b?.format!=='hammer-workshop-public-1'||!b.files)throw Error('Choose a Workshop public draft backup.');for(const p of PATHS)if(!b.files[p]||typeof b.files[p]!=='object'||Array.isArray(b.files[p]))throw Error('Backup missing '+p);for(const [p,key] of [['site-data/projects.json','projects'],['site-data/pages.json','pages'],['site-data/reviews.json','reviews'],['gallery.json','homePairs']])if(!Array.isArray(b.files[p][key]))throw Error('Invalid backup list: '+p);const errors=W.validateConfig(b.files[CONFIG]);if(errors.length)throw Error(errors.join(' '));for(const p of Object.keys(b.generated||{}))if(!/^project-[a-z0-9-]+\.html$/.test(p)&&p!=='sitemap.xml')throw Error('Invalid generated filename');for(const a of b.assets||[])if(!/^images\/owner\/[a-z0-9._-]+\.(webp|png|jpe?g|avif)$/.test(a.path)||!/^image\/(webp|png|jpeg|avif)$/.test(a.type))throw Error('Invalid backup image');for(const p of Object.keys(b.documents||{}))if(!W.safePath(p))throw Error('Invalid document name');return b;}

  on('photoFile','change',e=>loadPhoto(e.target.files[0]));for(const [id,out] of [['focusX','focusXValue'],['focusY','focusYValue'],['photoQuality','qualityValue']])on(id,'input',()=>{$(out).textContent=$(id).value+'%';renderPhoto();});on('photoCanvas','click',e=>{if(!photo)return;const r=$('photoCanvas').getBoundingClientRect(),scale=Math.min(r.width/$('photoCanvas').width,r.height/$('photoCanvas').height),w=$('photoCanvas').width*scale,h=$('photoCanvas').height*scale;$('focusX').value=Math.round(W.clamp((e.clientX-r.left-(r.width-w)/2)/w*100,0,100));$('focusY').value=Math.round(W.clamp((e.clientY-r.top-(r.height-h)/2)/h*100,0,100));$('focusXValue').textContent=$('focusX').value+'%';$('focusYValue').textContent=$('focusY').value+'%';renderPhoto();});on('makePhotos','click',preparePhotos);on('applyPhotos','click',addPhotos);
  on('projectSelect','change',()=>{projectIndex=+$('projectSelect').value;projectDraft=W.clone(projects()[projectIndex]);renderProject();});on('newProject','click',()=>{projects().push({title:'',summary:'',active:false,publishStatus:'draft',showOnHomepage:true,showInGallery:true,showLocation:true,midProcessImages:[],additionalImages:[],displayOrder:(projects().length+1)*10});projectIndex=projects().length-1;renderProjectSelect();remember();});on('saveProjectDraft','click',saveProject);on('buildProject','click',prepareProject);
  on('siteFolder','change',e=>{localFiles.clear();for(const f of e.target.files){const p=f.webkitRelativePath.split('/').slice(1).join('/');if(W.safePath(p)&&!/(^|\/)(node_modules|\.git)(\/|$)/.test(p))localFiles.set(p,f);}status(localFiles.size+' local files selected for read-only inspection.');});on('runInspect','click',inspect);on('saveInspect','click',()=>{if(!inspectReport)throw Error('Run an inspection first.');download('HammerBrick-Release-Report.json',inspectReport);});on('loadWall','click',loadWall);on('checkWall','click',checkWall);on('saveWall','click',()=>{if(!wallReport)throw Error('Check the wall first.');download('HammerBrick-Layout-Report.json',wallReport);});
  on('visualImport','change',async e=>{const f=e.target.files[0];if(f.size>30*1048576)throw Error('Screenshot report too large.');const report=JSON.parse(await f.text());if(report.format!=='hammer-workshop-visual-1')throw Error('Choose a Workshop visual test report.');$('screenshotWall').replaceChildren();for(const d of report.devices||[]){const tile=make('div');tile.className='tile';tile.append(make('b',d.name));if(/^data:image\/png;base64,/.test(d.preview||'')){const img=make('img');img.src=d.preview;img.alt=d.name+' screenshot';tile.append(img);}tile.append(make('small',(d.issues||[]).map(r=>r.message).join(' · ')||'No automatic layout warnings.'));$('screenshotWall').append(tile);}});
  on('addCert','click',addCertificate);on('saveVault','click',async()=>{if($('vaultPass').value!==$('vaultPassConfirm').value)throw Error('Passphrases do not match.');download('HammerBrick-PRIVATE-DO-NOT-UPLOAD.hbvault',await encryptVault(vault,$('vaultPass').value));vaultDirty=false;status('Encrypted vault downloaded separately. Keep it off GitHub and save your passphrase securely.');});on('vaultFile','change',async e=>{if(vaultDirty&&!confirm('Replace unsaved in-memory vault records?'))return;const f=e.target.files[0];if(f.size>45*1048576)throw Error('Vault file too large.');vault=await decryptVault(JSON.parse(await f.text()),$('vaultPass').value);vaultDirty=false;renderVault();status('Vault unlocked in memory only.');});on('lockVault','click',()=>{if(vaultDirty&&!confirm('Clear unsaved private records? Download an encrypted backup first to keep them.'))return;vault=[];vaultDirty=false;$('vaultPass').value='';$('vaultPassConfirm').value='';$('certNotes').value='';$('certDocument').value='';renderVault();status('Vault locked. Downloaded encrypted files remain untouched.');});on('syncTrust','click',()=>{if(!vault.length)throw Error('Open your vault or add verified records first.');config.publicTrust=W.publicCertificates(vault);renderTrustSummary();remember();});
  on('previewPrint','click',async()=>{lastPrint=await inlinePreparedImages(buildPrint());$('printFrame').srcdoc=lastPrint;});on('downloadPrint','click',async()=>{lastPrint=await inlinePreparedImages(buildPrint());download('HammerBrick-'+$('printType').value+'.html',lastPrint,'text/html');});on('printSheet','click',async()=>{const html=await inlinePreparedImages(buildPrint()),f=$('printFrame');if(f.srcdoc!==html){f.srcdoc=html;await new Promise(r=>f.onload=r);}f.contentWindow.focus();f.contentWindow.print();});on('downloadQr','click',()=>{const u=$('printUrl').value;if(!W.safeUrl(u))throw Error('Use a safe QR destination.');download('HammerBrick-QR.svg',W.qrSvg(new URL(u,BASE).href),'image/svg+xml');});on('runHealth','click',health);on('saveHealth','click',()=>{if(!healthReport)throw Error('Run a health test first.');download('HammerBrick-Health-Report.json',healthReport);});on('runSearch','click',search);on('downloadPackage','click',exportPackage);on('backupSettings','click',publicBackup);on('resetDraft','click',()=>{if(confirm('Discard this Workshop draft? Download changed files and your encrypted vault first.'))location.reload();});
  on('importSettings','change',async e=>{const f=e.target.files[0];if(f.size>70*1048576)throw Error('Backup exceeds 70 MB.');const b=validateBackup(JSON.parse(await f.text()));if(!confirm('Replace this Workshop draft with the backup? Nothing is published.'))return;for(const p of PATHS)files[p]=W.clone(b.files[p]);config=files[CONFIG];generated.clear();documents.clear();assets.clear();for(const [p,t] of Object.entries(b.generated||{}))generated.set(p,t);for(const [p,t] of Object.entries(b.documents||{}))documents.set(p,t);for(const a of b.assets||[])assets.set(a.path,new Blob([decode64(a.data)],{type:a.type}));initControls();refreshExport();status('Public draft backup restored in memory. Private vault is unchanged.');});
  window.addEventListener('beforeunload',e=>{if(vaultDirty||changedPaths().length||assets.size||generated.size){e.preventDefault();e.returnValue='';}});
  async function init(){try{await Promise.all(PATHS.map(async p=>{files[p]=await json(p);original[p]=W.clone(files[p]);}));let restored;try{restored=JSON.parse(sessionStorage.getItem('hammer-workshop-import')||'null');}catch{}if(restored){validateBackup(restored);PATHS.forEach(p=>files[p]=restored.files[p]);Object.entries(restored.generated||{}).forEach(([p,t])=>generated.set(p,t));Object.entries(restored.documents||{}).forEach(([p,t])=>documents.set(p,t));for(const a of restored.assets||[])assets.set(a.path,new Blob([decode64(a.data)],{type:a.type}));sessionStorage.removeItem('hammer-workshop-import');}config=files[CONFIG];const errors=W.validateConfig(config);if(errors.length)throw Error(errors.join(' '));ready=true;initControls();renderVault();refreshExport();status('Ready. Ten Workshop tools loaded; current site, designs and controls are unchanged.');}catch(e){status(e.message+' Upload all Workshop files, then open through your website or localhost.');}}
  window.HammerWorkshopApp={files,original,assets,generated,documents,changedPaths,scanDocument,renderedChecks,encryptVault,decryptVault,validateBackup,exportPackage,prepareProject,ready:()=>ready};init();
})();
