#!/usr/bin/env node
/* Manual local screenshots. No publishing, credentials, form submissions or remote writes. */
'use strict';
const fs=require('fs'),path=require('path'),http=require('http');
const args=process.argv.slice(2),arg=(key,fallback)=>{const i=args.indexOf(key);return i<0?fallback:args[i+1];};
const root=path.resolve(arg('--root',path.join(__dirname,'..'))),out=path.resolve(arg('--output',path.join(root,'workshop-test-results')));
const baseline=arg('--baseline',''),exe=arg('--browser','');
let chromium;
try{({chromium}=require('playwright'));}catch{console.error('Install the test-only dependency: npm install --no-save playwright\nThen: npx playwright install chromium');process.exit(2);}
if(!fs.existsSync(path.join(root,'index.html')))throw Error('Select the full website folder with --root.');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.xml':'application/xml'};
const server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost'),relative=decodeURIComponent(u.pathname).replace(/^\/+/,''),p=path.resolve(root,relative||'index.html');if(p!==root&&!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404).end('Not found');return;}res.setHeader('Content-Type',types[path.extname(p).toLowerCase()]||'application/octet-stream');res.setHeader('Cache-Control','no-store');if(req.method==='HEAD'){res.end();return;}fs.createReadStream(p).pipe(res);}catch{res.writeHead(400).end();}});
const sizes=[['small-iphone',375,667],['iphone-pro-max',430,932],['android',412,915],['tablet',768,1024],['laptop',1366,900],['desktop',1920,1080]];
async function examine(page){return page.evaluate(()=>{const issues=[],visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none';};if(document.documentElement.scrollWidth>innerWidth+2)issues.push({level:'fail',message:'Horizontal page overflow: '+document.documentElement.scrollWidth+' / '+innerWidth});for(const img of [...document.images].filter(visible)){if(img.complete&&!img.naturalWidth)issues.push({level:'fail',message:'Broken image: '+img.getAttribute('src')});if(!img.hasAttribute('alt'))issues.push({level:'warn',message:'Missing image alt: '+img.getAttribute('src')});const r=img.getBoundingClientRect();if(img.naturalWidth&&getComputedStyle(img).objectFit==='fill'&&Math.abs((r.width/r.height)/(img.naturalWidth/img.naturalHeight)-1)>.1)issues.push({level:'warn',message:'Possible stretched image: '+img.getAttribute('src')});}for(const el of [...document.querySelectorAll('button,input:not([type=hidden]),select,textarea')].filter(visible)){const r=el.getBoundingClientRect(),name=el.getAttribute('aria-label')||el.getAttribute('aria-labelledby')||el.textContent.trim()||[...(el.labels||[])].map(l=>l.textContent).join('');if(!name)issues.push({level:'warn',message:'Unlabelled control: '+(el.id||el.tagName)});if(r.width<24||r.height<24)issues.push({level:'warn',message:'Small touch target (review spacing/exceptions): '+(el.id||name)});}return issues;});}
async function main(){await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,...(exe?{executablePath:exe}:{})});const report={format:'hammer-workshop-visual-1',createdAt:new Date().toISOString(),devices:[],limits:'Chromium viewport emulation, not physical iOS Safari or a WCAG certificate. Third-party requests are blocked in this safe local test.'};try{for(const [name,width,height] of sizes){const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});await context.route('**/*',route=>{const u=new URL(route.request().url());return u.origin===origin?route.continue():route.abort();});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push({level:'warn',message:'JavaScript: '+e.message}));await page.goto(origin+'/',{waitUntil:'load',timeout:30000});await page.evaluate(async()=>{await document.fonts.ready;for(let y=0;y<document.body.scrollHeight;y+=600){scrollTo(0,y);await new Promise(r=>setTimeout(r,35));}scrollTo(0,0);});await page.waitForTimeout(700);const issues=[...errors,...await examine(page)],png=await page.screenshot({path:path.join(out,name+'.png'),fullPage:true,animations:'disabled'}),preview=await page.screenshot({fullPage:false,animations:'disabled'});const row={name,width,height,screenshot:name+'.png',preview:'data:image/png;base64,'+preview.toString('base64'),issues};if(baseline){const previous=path.join(path.resolve(baseline),name+'.png');row.baselineComparison=fs.existsSync(previous)?(fs.readFileSync(previous).equals(png)?'Identical PNG bytes':'Changed screenshot; compare visually. Pixel difference is not automatically an error.'):'No baseline screenshot.';}report.devices.push(row);await page.goto(origin+'/admin/workshop.html',{waitUntil:'load'});await page.waitForFunction(()=>window.HammerWorkshopApp?.ready(),{},{timeout:15000});await page.screenshot({path:path.join(out,'admin-'+name+'.png'),fullPage:false,animations:'disabled'});await context.close();}
fs.writeFileSync(path.join(out,'visual-report.json'),JSON.stringify(report,null,2)+'\n');console.log('Screenshots and importable visual-report.json saved to '+out);const failures=report.devices.flatMap(d=>d.issues).filter(i=>i.level==='fail').length;if(failures){console.error(failures+' layout/image failures need review.');process.exitCode=1;}}finally{await browser.close();}}
main().catch(e=>{console.error(e.message);process.exitCode=2;}).finally(()=>server.close());
